ALTER TABLE projects ADD COLUMN IF NOT EXISTS image_style TEXT NOT NULL DEFAULT 'realistic';
ALTER TABLE projects ADD COLUMN IF NOT EXISTS logo_path TEXT;

ALTER TABLE profiles ADD COLUMN IF NOT EXISTS logo_path TEXT;
